In [58]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
import pandas as pd
import pickle

In [59]:
model = load_model("model.h5")

with open("label_encoder_gender.pkl",'rb') as file:
    label_encoder_gender = pickle.load(file)

with open("onehotencoder_geo.pkl" , 'rb') as file:
    ohe_geo = pickle.load(file)

with open("scaler.pkl",'rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [78]:
input_data = {'CreditScore': 500,
 'Geography': 'France',
 'Gender': 'Male',
 'Age': 30,
 'Tenure': 2,
 'Balance': 50000,
 'NumOfProducts': 1,
 'HasCrCard': 1,
 'IsActiveMember':1,
 'EstimatedSalary':60000,}

In [79]:
new_df  = pd.DataFrame([input_data])

In [80]:
new_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,500,France,Male,30,2,50000,1,1,1,60000

In [81]:
new_df['Gender']  = label_encoder_gender.transform([new_df['Gender']])

c:\Users\M S I\Desktop\ANN_Classification_Project\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [82]:
new_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,500,France,1,30,2,50000,1,1,1,60000

In [83]:
geo_df = pd.DataFrame(data=ohe_geo.transform([new_df['Geography']]).toarray() , columns=ohe_geo.get_feature_names_out())

c:\Users\M S I\Desktop\ANN_Classification_Project\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [84]:
geo_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [85]:
new_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,500,France,1,30,2,50000,1,1,1,60000

In [86]:
final_df = pd.concat([new_df.drop(columns=['Geography']) , geo_df ],axis=1)

In [87]:
new_df.drop(columns=['Geography'])

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,500,1,30,2,50000,1,1,1,60000

In [88]:
final_df = scaler.fit_transform(final_df)

In [89]:
model.predict(final_df)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step

array([[0.24768652]], dtype=float32)

In [94]:
label_encoder_gender.classes_

array(['Female', 'Male'], dtype=object)

In [91]:
ohe_geo.categories_[0]

array(['France', 'Germany', 'Spain'], dtype=object)